### ISSUE TITLE
Update METviewer to handle changes in met-9.1.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#185]
## Describe the Enhancement ##
Listed below are the changes in met-9.1 which impact METviewer:

1. Add new RPS_COMP to the end of the RPS line type: https://github.com/NCAR/MET/issues/1280
RPS_COMP stands for the "Complement of the Ranked Probability Score" which can be used as the tooltip.  It is computed simply as RPS_COMP = 1 - RPS.

For the old MET output that doesn't have RPS_COMP, calculate the value using the formula and insert it into the new column

### Time Estimate ###
1 day.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- No sub-issues needed

### Relevant Deadlines ###
None

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: Tatiana Burek
- [X] Select **scientist(s)** or **no scientist** required: no scientist needed

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts to other METplus components.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [x] Add/update unit tests.
- [ ] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by TatianaBurek** [comment]
The typo was made. Rename RPSS_COMP to RPS_COMP

**Comment by TatianaBurek** [comment]
Add RPS_COMP to the list of aggregation statistics

**Comment by TatianaBurek** [comment]
Add RPS_COMP to scorecard

**Comment by TatianaBurek** [comment]
Add RPS_COMP to python
