### ISSUE TITLE
discontinue  ‘norm’,’ basic’, ‘bca’, ‘stud’ CI methods

### ISSUE THREAD

**Issue by TatianaBurek** [NCAR/METviewer#192]
## Describe the Task ##
*Python boot library implements  only percentile method. Remove other methods from UI*
https://github.com/NCAR/METcalcpy/issues/15

### Time Estimate ###
*Issues should represent approximately 1 hour.*

### Relevant Deadlines ###
*NONE.*

### Funding Source ###
*NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
