### ISSUE TITLE
METviewer Documentation

### ISSUE THREAD

**Issue by lindsayrblank** [NCAR/METviewer#204]
*Replace italics below with details for this issue.*

## Describe the Task ##
Update and add to existing METviewer documentation. Need to add the following to Chapter 3 - 13:
1. Description
2. Step by step instructions
3. Example plot
4. Example xml

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*
At least 3 days, probably more, will adjust once I have a better idea of the work that needs to be done. 

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] Chapter 3: Series Plots
- [x] Chapter 4: Bar Plots
- [x] Chapter 5: Box Plots
- [x] Chapter 6: ROC Plots
- [x] Chapter 7: Reliability Plots
- [x] Chapter 8: Performance Diagram
- [x] Chapter 9: Taylor Diagram
- [x] Chapter 10: Contour Plots
- [x] Chapter 11: Spread/Skill Plots
- [x] Chapter 12: ECLV
- [x] Chapter 13: Scorecards

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*
Sept. 30?

### Funding Source ###
2712231

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: Julie Prestopnik 
- [X] Select **scientist(s)** or **no scientist** required: Lindsay Blank and Tara Jensen

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
Tatiana, thank you for making updates to installation.rst.  I asked Lisa to make a few minor formatting changes, so she is working on that file now.  I have a question for you though.  This text references CVS:
`check out test_data (.../apps/verif/metviewer_test_data/test_data/) from CVS and move test_data directory to /d3/projects/METViewer/:`
Is that correct?  If so, can you please tell us what the three dots represent here:  ".../apps" and also what the colon at the end of the directory path (/d3/projects/METViewer/:) represents?  Thanks!

**Comment by jprestop** [comment]
Moved testing.rst to a Contributors_Guide section and set up an index.rst file for the Contributors_Guide.  I had originally added docs/Contributors_Guide to the .gitignore file, but it turns out that is not necessary as long as "Contributors_Guide" is not referenced in the docs/index.rst file.  We will get a warning "checking consistency... ...METviewer/docs/Contributors_Guide/index.rst: WARNING: document isn't included in any toctree", but I think that is better than leaving it in .gitignore, forgetting about it, and then trying to debug why it isn't there.  The warning will remind us to add it when we are ready to deploy it.
