### ISSUE TITLE
Enhance METviewer to load the additional CRPS columns in the ECNT line type updated for met-10.0.0.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#259]
## Describe the Enhancement ##
dtcenter/MET#1450 adds CRPS-related columns to the end of the existing ECNT line type produced by Ensemble-Stat. The updated line type will be available in the met-10.0.0-beta4 release. This task is to enhance METviewer to load the updated contents of the ECNT line type for MET version 10.0.0.

@JohnHalleyGotway will provide an updated sample data file as soon as one is available.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
METplus 4.0 release

### Funding Source ###
?

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: Tatiana
- [x] Select **scientist(s)** or **no scientist** required: no scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- dtcenter/MET#1450
- dtcenter/METdatadb#48

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Please find updated version of the ECNT line type for met-10.0.0 attached:
[sample_ecnt.tar.gz.txt](https://github.com/dtcenter/METviewer/files/6066111/sample_ecnt.tar.gz.txt)
(Note: added .txt to the tarfile name to trick GitHub)

**Comment by TatianaBurek** [comment]
Attached sample_ecnt.tar.gx file contains .txt files that are not compatible with METviewer. METviewer needs .stat files

**Comment by JohnHalleyGotway** [comment]
Please find sample .stat files here which contain both updated ECNT and ORANK lines:
[sample_ens_stat.tar.gz](https://github.com/dtcenter/METviewer/files/6069895/sample_ens_stat.tar.gz)

Please see the header lines in sample_ecnt.tar.gz and sample_orank.tar.gz for the names of the new columns.
Note that in ORANK, the existing CLIMO column was renamed as CLIMO_MEAN.

**Comment by TatianaBurek** [comment]
New stats were added to UI as non-aggregation stats

**Comment by JohnHalleyGotway** [comment]
Tatiana,

The new CRPSCL, CRPS_EMP, CRPSCL_EMP, and CRPSS_EMP columns can and should be aggregated in the same way that the existing CRPS and CRPSS columns are aggregated. Or is METviewer not yet able to aggregate those?

If not, let's define a new issue to define the aggregation logic for these CRPS stats.
If so, then let's aggregate the new CRPS stats in the same way the existing ones are aggregated.

The aggregation logic is pretty straight-forward:
- Aggregate CRPS, CRPSCL, CRPS_EMP, and CRPSCL_EMP as weighted averages of the input values.
- Like elsewhere, the weights are defined by the number of matched pairs, as indicated by the TOTAL column.
- Once CRPS and CRPSCL have been aggregated, define the aggregated CRPSS = 1 - CRPS/CRPSCL.
- Likewise, once CRPS_EMP and CRPSCL_EMP have been aggregated, define the aggregated CRPSS_EMP = 1 - CRPS_EMP/CRPSCL_EMP.

This logic can be found implemented in MET starting on this line:
https://github.com/dtcenter/MET/blob/996197cff8c7272906602de8245ae26cd91549d5/met/src/libcode/vx_statistics/ens_stats.cc#L231

**Comment by TatianaBurek** [comment]
METviewer calculates ECNT_CRPSS using crps_climo and not crps.

https://github.com/dtcenter/METviewer/blob/8ae628a026414ea57285736970dff8fbc957f877/R_work/include/statistics.R#L798
where crps_climo:
https://github.com/dtcenter/METviewer/blob/8ae628a026414ea57285736970dff8fbc957f877/R_work/include/util_plot.R#L1285

Should I calculate crps_emp_climo in the similar way and then use it for CRPSS_EMP calculation or just use CRPS_EMP?

**Comment by TatianaBurek** [comment]
Corresponding issue is added to METcalcpy:
https://github.com/dtcenter/METcalcpy/issues/69

**Comment by JohnHalleyGotway** [comment]
I would recommend keeping the existing logic as-is. It will work for output from older versions of MET and it will also work for newer versions of MET:
```
crps_climo = as.numeric( d[[ paste(strPerm, "crps", sep="_") ]] ) / (1.0 - as.numeric( d[[ paste(strPerm, "crpss", sep="_") ]] ))
```

For the empirical scores (with the _EMP suffix), please just use the "CRPSCL_EMP" score from the MET version 10.0.0 ECNT line type.

Another option is the following... but it may be too hard:
- the schema will change for met-10.0.0 since we're adding new columns for CRPSCL, CRPS_EMP, CRPSCL_EMP, and CRPSS_EMP
- we'll need to write a script to update existing databases to the new schema version
- rather than simply updating existing databases by setting CRPSCL = NA, we could instead have that script set CRPSCL = CRPS / (1.0 - CRPSS)

If updating the existing databases in this way isn't too hard, that's what I'd recommend.
If it is too hard, then use the old logic for deriving CRPSCL from CRPSS and CRPS. But for _EMP versions, using the simpler logic.

**Comment by TatianaBurek** [comment]
1. Calculation of the CRPSCL values in the 'line_data_ecnt' table column for the old data is added to the database update script. It will be performed on all database on dakota, mohawk, AWS before METviewer 4.0 update. This script will be shared with GSD
2. Implementation of the calculation of ECNT_CRPSS in Rscript statistics.R is updated to use CRPSCL value from database
3. Calculation of crps_climo is removed from util_plot.R calcSeriesSums method.
