### ISSUE TITLE
Enhance METviewer to load the additional climatology column in the ORANK line type updated for met-10.0.0. 

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#261]
## Describe the Enhancement ##
dtcenter/MET#1451 makes two changes to the ORANK line type created by Ensemble-Stat. It renames the existing column from CLIMO to CLIMO_MEAN and addends a new column to the end of the line names CLIMO_STDEV. The updated line type will be available in the met-10.0.0-beta4 release. This task is to enhance METviewer to load the updated contents of the ORANK line type for MET version 10.0.0.

@JohnHalleyGotway will provide an updated sample data file as soon as one is available.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
METplus 4.0 release

### Funding Source ###
?

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: Tatiana
- [x] Select **scientist(s)** or **no scientist** required: no scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- dtcenter/MET#1451
- dtcenter/METdatadb#49

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Please find updated version of the ORANK line type for met-10.0.0 attached:
[sample_orank.tar.gz.txt](https://github.com/dtcenter/METviewer/files/6066113/sample_orank.tar.gz.txt)
(Note: added .txt to the tarfile name to trick GitHub)

**Comment by TatianaBurek** [comment]
Attached sample_orank.tar.gx file contains .txt files that are not compatible with METviewer. METviewer needs .stat files

**Comment by JohnHalleyGotway** [comment]
Please see this comment to METviewer #259 for sample stat data:
https://github.com/dtcenter/METviewer/issues/259#issuecomment-789011255

**Comment by TatianaBurek** [comment]
ORANK_CLIMO_STDEV is added to UI
CLIMO was renamed to CLIMO_MEAN

**Comment by TatianaBurek** [comment]
OBS_QC column form ORANK and MPR line types have type double but while PB2NC stores quality control values as integers (lower is better), in MADIS, they're stored as strings. So in MET, we store and write them as strings.
METviewer should change the type pf these columns to strings
