### ISSUE TITLE
Create a singularity container for METviewer

### ISSUE THREAD

**Issue by hankenstein2** [NCAR/METviewer#281]
*Replace italics below with details for this issue.*

## Describe the Enhancement ##
Most HPCs are not allowing Docker containers but they do allow singularity. We need to look into creating
A singularity container for METviewer

### Time Estimate ###
3 days or more

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
UAE-NCM has the most immediate requirement

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select  **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment]
@georgemccabe ans @bikegeek can you think about whether what Hank says in this issue is relevant for what we discussed today? If so, I can incorporate this into the workflow for NRL and add more details to the issue.

Minna, I tagged you since METviewer is called out specifically here, but this sounds mostly like a container issue.

**Comment by bikegeek** [comment]
If NRL is interested in creating scorecards from METviewer, then this would be useful since scorecards can only be generated via the command line.

**Comment by bikegeek** [comment]
Closing, as this is a duplicate of this issue: https://github.com/dtcenter/METviewer/issues/446
