### ISSUE TITLE
Add support for plotting new G and GBETA statistics.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#324]
## Describe the Enhancement ##
The issue dtcenter/met#1673 and corresponding pull request dtcenter/met#1857 add new columns to the distance map (DMAP) line type created by the Grid-Stat tool.

This adds 3 new columns to the end of the existing DMAP line type: G, GBETA, and BETA_VALUE. All 3 columns are floating point numbers. METviewer should be enhanced to plot the G and GBETA statistics. The BETA_VALUE is informational and likely does not need to be plotted. G and GBETA do not need to be aggregated across multiple cases. Instead, just plot them using summary options, like mean and median.

Note that G will always have a value in the output, but GBETA and BETA_VALUE will only have a value when VX_MASK = FULL. When VX_MASK != FULL, GBETA = BETA_VALUE = NA.

Check with @ericgilleland (also assigned to this issue) to see if METviewer should be enhanced to error out or print a warning message when plotting GBETA while the corresponding BETA_VALUE changes. Also, @ericgilleland should confirm that G and GBETA should not be aggregated over multiple cases in some way... and that computing summary statistics is appropriate.

Please see METdatadb issue for loading this new output into the statistics database:
dtcenter/METdatadb#62

Corresponding issue in METplotpy:
https://github.com/dtcenter/METplotpy/issues/142

Please see existing documentation for more details about the [configuration options](https://met.readthedocs.io/en/develop/Users_Guide/grid-stat.html?highlight=gbeta#distance-map), [science](https://met.readthedocs.io/en/develop/Users_Guide/grid-stat.html#beta-and-g-beta), and [equations](https://met.readthedocs.io/en/develop/Users_Guide/appendixC.html?highlight=gbeta#g-and-g-beta).

Sample data can be found in kiowa:/d1/projects/MET/MET_regression/develop/NB20210818/MET-develop/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V_dmap.txt.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
Prior to the coordinated METplus 4.1.0 release.

### Funding Source ###
2702691

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: Tatiana
- [x] Select **scientist(s)** or **no scientist** required: Eric

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by TatianaBurek** [comment]
@JohnHalleyGotway  does this issue require  work in METdatadb as well? Is there any corresponding issues in METdatadb?

**Comment by TatianaBurek** [comment]
the schema was updated and G and GBETA stats were added.
Mo checks or messages were implemented yet

**Comment by ericgilleland** [comment]
Re: Check with [Eric] (also assigned to this issue) to see if METviewer should be enhanced to error out or print a warning message when plotting GBETA while the corresponding BETA_VALUE changes. 

Eric Response: Yes, it probably would be good to print a warning along the lines of: "note that beta_value differs for one or more Gbeta values plotted so that comparisons across cases may not be comparable."

Also, [Eric] should confirm that G and GBETA should not be aggregated over multiple cases in some way... and that computing summary statistics is appropriate.

Eric Response: I agree that it is best to just plot them and not aggregate them over cases, at least for Gbeta.  G could be averaged across cases.

**Comment by TatianaBurek** [comment]
@ericgilleland if beta_value differs for one or more Gbeta values, should I gust print the warning and create a plot anyway or print an error and nor create a plot?

**Comment by ericgilleland** [comment]
I would still make the plot, but print a warning.
