### ISSUE TITLE
Enhance METviewer to plot SS_INDEX from the new SSIDX STAT line type.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#327]
## Describe the Enhancement ##
The pull request dtcenter/MET#1892 for issue dtcenter/MET#1788 adds a new STAT line type that is created by Stat-Analysis. The SSIDX line type is documented in the Stat-Analysis MET User's Guide chapter on the [feature branch](https://met.readthedocs.io/en/feature_1788_ssidx/Users_Guide/stat-analysis.html#id10). After that PR is approved/merged, please see the [develop branch](https://met.readthedocs.io/en/develop/Users_Guide/stat-analysis.html#id10) instead.

The SS_INDEX column contains the key statistic. However, there is no way to aggregate this across multiple cases. Instead, we'd just plot this using the summary method (e.g. mean or median). We should also be able to plot it as a boxplot. @michelleharrold and @hertneky can provide additional data for testing and validate the resulting plots.

The columns for FCST_MODEL, REF_MODEL, N_INIT, N_TERM, and N_VLD are purely information and do not need to be plotted.

Please ask @JohnHalleyGotway any questions about how to handle the data.

A sample data file is provided here:
[ssidx_sample.tar.gz](https://github.com/dtcenter/METviewer/files/7100427/ssidx_sample.tar.gz)

One file with FCST_VAR = OBS_VAR = GO_INDEX.
One file with FCST_VAR = OBS_VAR = SS_INDEX.
Another option is CBS_INDEX but no example is provided here.
Note that strings in the header columns can get long. For example, MODEL = fcst model name, reference model name. By default, when multiple strings are encountered in the input, their unique values are written to the output as a comma-separated list.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
To be included in the coordinated METplus version 4.1.0 release.

### Funding Source ###
Funded via the DTC AF project (2712221). See @michelleharrold.

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: Tatiana
- [x] Select **scientist(s)** or **no scientist** required: no scientist needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [x] Source issue in MET: dtcenter/MET#1788
- [x] Related issue in METdatadb to load this data: dtcenter/METdatadb#63
 
## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@michelleharrold and/or @hertneky can provide additional SSIDX test data after running it for the AF LIS project.

**Comment by TatianaBurek** [comment]
@JohnHalleyGotway currently we have a length limit for the model field/column in DB and it is 40 chars.
Do you think that this field will be longer than 40 chars? What would be the optimal length?

**Comment by JohnHalleyGotway** [comment]
Tatiana,

If the existing MODEL column has a limit of 40 characters, then I'd
recommend that that MODEL column be set to 80 characters, but that's only
needed for the SSIDX line type. If it's easy and convenient to support
MODEL as 80 characters for SSIDX and MODEL as 40 characters for all other
line types, then that's what I'd recommend. If we'd need to increase the
MODEL to 80 characters for ALL line types, then I wouldn't recommend that.
The SSIDX line type needs to be supported, but in general will probably be
pretty lightly used.

John

**Comment by TatianaBurek** [comment]
SSIDX line type will share existing stat_header table for the header columns. So yes, in order to accommodate SSIDX model name we have to increase the MODEL column to 80 chars for all line types.
If we leave 40 chars limit, should we chop SSIDX's model to fit in?

**Comment by JohnHalleyGotway** [comment]
@michelleharrold and @hertneky I'm wondering if you two have an opinion on this question? Currently METviewer reserves a field of length 40 characters to store the contents of the MODEL name column. For the SSIDX column, the MODEL column contains "forecast model name, reference model name". With those two concatenated, we're more likely to exceed 40 characters. But any change to the MODEL column will apply to all line types, not just SSIDX.

How should we handle this situation? Leave the 40 character limit as is, double it to 80, or perhaps pick the mid-point of 60?

**Comment by michelleharrold** [comment]
@JohnHalleyGotway, @TatianaBurek, @hertneky  - while I tend to agree model names should be concise and well under the current 40 character limit, I did stumble upon a model name being used in the SRW app that is "FV3_GFS_v15p2_CONUS_25km_mem1" - 30 characters! So while it is not likely to happen much, to avoid future scenarios needing a character increase, perhaps its best to increase to 80 now?

**Comment by TatianaBurek** [comment]
The size of the 'model' column is increased to 80 chars

**Comment by TatianaBurek** [comment]
@JohnHalleyGotway  @michelleharrold  @hertneky 
There is a conflict between METviewer notation standards and the comma-separated model name in SSIDX line type (UM,LIS)
If METviewer receives this XML
`  <series1>
            <field name="model">
                <val>UM,LIS</val>
            </field>
        </series1>`
it treats this value as two models grouped together and not as a single model.
Would it be possible for MET users to use different character as a separator for two models in SSIDX line type?
 For example, '\~',  or  ':'  (UM~LIS)
Otherwise we need to change the grouping notation and corresponding logic

**Comment by JohnHalleyGotway** [comment]
@TatianaBurek this is interesting. I'm wondering if this issue is specific to the MODEL column of the SSIDX line type or is it a bigger issue (see below)?

So the STAT-Analysis tool can write .stat output files, as of a few versions ago. For each of the header columns, it keeps track of the unique entries it encounters there. For columns with times in them, it reports the minimum or maximum time values, but for strings (like MODEL, DESC, VX_MASK, FCST_VAR, FCST_LEV) it keeps track of the unique input strings. And by default, it writes those unique strings as a comma-separated list to the output.

For example, if VX_MASK = "EAST" and "WEST" in the input, it'll write VX_MASK = "EAST,WEST" to the output.

Does this issue extend beyond just the MODEL column of the SSIDX line type? Would having VX_MASK = "EAST,WEST" cause the same problem? If so, we could switch from Stat-Analysis writing a comma-separated list to a colon separated list "EAST:WEST".

**Comment by TatianaBurek** [comment]
This issue is not specific to the MODEL column and affects all columns that can be selected as a series variable and grouped.  That would  include any non-statistical column.
Using your example, if METviewer receives <val>EAST,WEST</val> in the fix_val section it would use it as one value. But if the same value would be in the <series1/2> section for METviewer it would be like two separate masks in one  group.
Looking through the code I released that FCST_THRESH and OBS_THRESH already break this rule. They can be used as series variables and can have comma-separated values that would lead to the incorrect plot. 
We can: 
1. Leave  Stat-Analysis as-is using ',' as a separator but find a different character  for grouping in METviewer.
    Pros:
         -  No change in MET
         -  fix possible bug with FCST_THRESH
    Cons: 
         - Changes in METviewer/calcpy/plotpy
         -  retrain users to use a new character in XML and change old XML files
2. Make the change in Stat-Analysis to use some other character and leave METviewer as-is
    reverse Pros and Cons from 1

**Comment by JohnHalleyGotway** [comment]
@TatianaBurek I'm torn on this, but I lean toward addressing this in METviewer instead of changing the separator in MET... mostly because the FCST_THRESH and OBS_THRESH columns already break the rule.

If we update MET to switch from comma to colon (or something else), that won't be available until version 10.1.0. And many users will continue running older versions of MET to generate output. So this issue will remain with us for a long time.

I think that handling this in the METplus Analysis suite will get us past this issue more quickly.

**Comment by TatianaBurek** [comment]
I created issues to change the separator in MET/viewer/calcpy/plotpy
https://github.com/dtcenter/METviewer/issues/334
https://github.com/dtcenter/METplotpy/issues/152
https://github.com/dtcenter/METcalcpy/issues/117
