### ISSUE TITLE
Make METdatadb the primary loading method

### ISSUE THREAD

**Issue by TatianaBurek** [NCAR/METviewer#350]
## Describe the Task ##
Currently METviewer Java classes are used as a default to load data to the database.
Need to change the mv_load.sh to use METdatadb instead, remve mv_load_pythn.sh and create mv_load_java.sh
Also need to modify METviewer regression testing procedure by replacing Java loader with Python 

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 2 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] Change scripts
- [x] Modify testing
- [x] Modify Dockerfile

### Relevant Deadlines ###
*NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by venitahagerty** [comment]
Note that the tag verbose can be set to true and you'll get more output.

From my work so far, it looks like METdbload thinks it has a mode file - which is weird. I think that's in reference to grid_stat_POP_12_1080000L_20050808_000000V.stat. I'll continue looking into this.
