### ISSUE TITLE
Reestablish Revision series 

### ISSUE THREAD

**Issue by TatianaBurek** [NCAR/METviewer#394]
## Describe the Task ##
The original Revision series for series and box plot were added to METviewer in v2.6
METviewer was calculating revision data and statistics and plot them. Tressa's opinion was that:
"It is not the revision statistics that are complex, it is keeping the time series data associated in the database that may prove difficult. Databases are better designed for independent cases, which revisions are not. 
This is probably a solved problem in database design, but I have no time to investigate." So we remove this capability: https://github.com/dtcenter/METviewer/issues/149.
Some revision statistics for MODE-TD were added later. Here is the issue for the MTD Revision statistics (with Tressa's comment) where I calculated  MTD Revision Stats from the MTD revision data. This feature was added on Aug 20, 2019.
My understanding was that the revision data was already calculated by MET???  since there were some issues calculating it in METviewer based on the previous discussion.
https://github.com/dtcenter/METviewer/issues/111

Since here is scientific value to having this capability even if it's not statistically robust we should reestablish the original Revision series  by putting back UI components and implement revision_box_plot.R_tmpl and revision_series_plot.R_tmpl in Python. Here is the documentations written by Tressa:
[Revision.History.manual.pdf](https://github.com/dtcenter/METviewer/files/8755416/Revision.History.manual.pdf)

https://github.com/dtcenter/METplotpy/issues/232
https://github.com/dtcenter/METcalcpy/issues/181

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 5 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2700042

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
