### ISSUE TITLE
Plot new columns added to the MET-11.0.0-beta1 output.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#403]
## Describe the Enhancement ##
Several new columns of "stat" output were added to the output of MET version 11.0.0-beta1. This issue is to update the database schema to handle these changes. We also need to update METviewer to display the columns in the GUI and plot some of them.

Note: I can't see a need to actually PLOT the contents of the EC_VALUE column described below. However we should only aggregate CTC tables together when the EC_VALUE remains constant. Doing otherwise should result in an error.

- Issue dtcenter/MET#2147:
   - Adds EC_VALUE to the end of the CTC line type
      - Value between 0.0 and 1.0 to indicate the expected correct rate
      - Fill existing CTC tables with a default EC_VALUE of 0.5
      - Only aggregate CTC tables where the EC_VALUE remains constant
   - Adds 4 new columns to the end of the CTS line type: HSS_EC HSS_EC_BCL HSS_EC_BCU EC_VALUE
      - HSS_EC is the Heidke Skill Score using the user-configurable expected correct rate. See details in [Appendix C](https://met.readthedocs.io/en/develop/Users_Guide/appendixC.html?highlight=hss_ec#heidke-skill-score-expected-correct-hss-ec). 
      - The _BCL and _BCU columns are the bootstrap CI limits.
      - The EC_VALUE is as described in the CTC column. Don't see a need to actually plot this.

- Issue dtcenter/MET#2022:
   - Adds 2 columns to the end of the VAL1L2 line type: FA_SPEED_BAR and OA_SPEED_BAR
      - These correspond to the VL1L2 line type's F_SPEED_BAR and O_SPEED_BAR columns but for the anomalies (F-C and O-C) instead
   - Adds 8 new columns to the end of the [VCNT line type](https://met.readthedocs.io/en/develop/Users_Guide/point-stat.html#id23):
   - Centered Anomaly Correlation with normal and bootstrap CI's
      - ANOM_CORR, ANOM_CORR_NCL, ANOM_CORR_NCU, ANOM_CORR_BCL, ANOM_CORR_BCU
   - Uncentered Anomaly Correlation with bootstrap CI's
      - ANOM_CORR_UNCNTR ANOM_CORR_UNCNTR_BCL ANOM_CORR_UNCNTR_BCU

In the MCTC and MCTS line types, the default would be 1/N where N is the dimension of the Nx2 contingency table. 
Only aggregate MCTC and  MCTS tables where the EC_VALUE remains constant

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2792541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @TatianaBurek  
- [x] Select **scientist(s)** or **no scientist** required: Please ask @JohnHalleyGotway if questions arise

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Please find some recent output from the nightly build of the develop branch posted here:
ftp://ftp.rap.ucar.edu/incoming/irap/met_help/MET-11.0.0_data/NB20220706_MET_test_output.tar.gz

**Comment by TatianaBurek** [comment]
@JohnHalleyGotway Please explain what you mean "Only aggregate CTC tables where the EC_VALUE remains constant".
When this requirement applies? For calculating all CTC/CTS statistics?
Do we need to plot CTC EC_VALUE?

**Comment by TatianaBurek** [comment]
@JohnHalleyGotway  I assume that we don't need to plot FA_SPEED_BAR and OA_SPEED_BAR. How to use them?
Should we plot VCNT ANOM_CORR_UNCNTR and ANOM_CORR? Should we calculate them as Sum and Agg stats ?

**Comment by JohnHalleyGotway** [comment]
Sorry for the delay Tatiana, I'd written up a response, but never sent it!?

When computing aggregated CTS statistics, we aggregate the CTC lines first.
Those CTC lines now include the EC_VALUE column. If the EC_VALUE is
constant across all the CTC lines, proceed with the aggregation. If it is
not, error out with a message indicating that.

I think you might as well plot FA_SPEED_BAR and OA_SPEED_BAR... in the same
way you'd plot F_SPEED_BAR and O_SPEED_BAR.

Yes, we should plot VCNT ANOM_CORR_UNCNTR and ANOM_CORR. Yes, we should
support their aggregation.

The VL1L2 aggregation logic can be seen here:
https://github.com/dtcenter/MET/blob/c0d6397b88bfcd6b4ae64e289c6c29994f856dc8/src/libcode/vx_statistics/met_stats.cc#L1330

And the derivation of these stats from the Vector partial sums can be seen
here:
https://github.com/dtcenter/MET/blob/c0d6397b88bfcd6b4ae64e289c6c29994f856dc8/src/libcode/vx_statistics/met_stats.cc#L1754

Thanks,
John

**Comment by TatianaBurek** [comment]
- We don't user CTS table in the aggregation logic so CTS EC_VALUE can't be included into METviewer

- We don't plot  F_SPEED_BAR and O_SPEED_BAR. We use them for calculating VL1L2_WIND_DIFF and VL1L2_FVAR

**Comment by JohnHalleyGotway** [comment]
Thanks for clarifying. Those considerations make sense to me. Please let me know if there's any remaining questions I can help answer.
