### ISSUE TITLE
Enhance METviewer to plot statistics added to the ECNT, VL1L2, VAL1L2, and VCNT line types introduced in the MET 12.0.0 beta4 development cycle

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#517]
## Describe the Enhancement ##
Issue dtcenter/METdataio#282 updates the schema to load new wind direction statistics from the VL1L2, VAL1L2, and VCNT line types and new ignorance score statistics to the ECNT line type for MET version 12.0.0 . This issue is to update METviewer to provide access to these new statistics both via the web interface and through the backend XML files, as needed.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [x] dtcenter/MET#2395
- [x] dtcenter/METdataio#282
- [x] dtcenter/METcalcpy#361
- [x] dtcenter/METviewer#517

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by bikegeek** [comment]
add the new columns in the java/src/edu/ucar/metviewer/MVUtil.java code:

ECNT: IGN_CONV_OERR, IGN_CORR_OERR

VL1L2: DIR_ME, DIR_MAE, DIR_MSE
VAL1L2: DIRA_ME, DIRA_MAE, DIRA_MSE
VCNT: DIR_ME, DIR_MAE, DIR_MSE, DIR_ME_BCL, DIR_ME_BCU, DIR_MAE_BCL, DIR_MAE_BCU, DIR_MSE_BCL, DIR_MSE_BCU

**Comment by bikegeek** [comment]
The scorecard code also required updating: scorecard.db.AggDatabaseManagerMySQL.java for the VL1L2, VAL1L2, and ECNT linetypes.  According to the METviewer documentation, there is no support for VCNT which is consistent with the code as support for VCNT is not available in this method.

**Comment by bikegeek** [comment]
Added **_boolAggVcnt=#<agg_vcnt>#;_** to the agg_stat_info_tmpl
