### ISSUE TITLE
Optimize the METviewer Docker image creation process

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#527]
## Describe the Enhancement ##
These ideas arose during development for issue #521. The `sonarqube.xml` workflow uses Docker to build METviewer prior to scanning the code. Note that that image is built locally and NOT pushed up to DockerHub. However, we could add a `metviewer-dev` DockerHub repo if/when needed to facilitate additional testing.

METviewer currently contains 3 Dockerfile variations: `Dockerfile`, `Dockerfile.copy`, and `Dockerfile.apptainer`. I recommend making the following enhancements to this setup.

- [x] Switch from using the deprecated `centos7` as the base image to using an updated version of the `dtcenter/met-base` image (see https://github.com/dtcenter/METbaseimage/issues/23).
- [x] A LOT of functionality is duplicated in these 3 files. Factor out the commonality into an `internal/scripts/docker/build_metviewer_docker.sh` script and update the Dockerfiles to call it.
- [ ] Enhance the logic in `internal/docker/hooks/build` to properly handle the version dependencies between METviewer and the METplus-Analysis tool components.
- [x] No other automated testing of METviewer exists. Recommend defining a `testing.yml` workflow similar to the other METplus repositories to build METviewer in Docker and run a series of regression tests on the result. However, this work could also be done in a separate issue -- not done for this issue. Moved to new METviewer#539 issue.

### Time Estimate ###
2 days?

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [x] Depends on dtcenter/METbaseimage#23.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hankenstein2** [comment]
Updating the METviewer Dockerfile
need to remove dependency on CentOS (no more support after next month)
Debian 12 should be the OS
Get the current docker compose file working with debian 12 along with the latest release of Tomcat/Apache/Java that works with METviewer
John H.G. to look for what Java version we are using
Tomcat 9.0.x, 10.1.x work with Java 8.x
Current Tomcat is 9.0.80 we should test with Tomcat 9.0.89
need to update the Tomcat version for Jonathan Vigh and NRIT on ‘urma’ to address security vulnerabilities
See related [METviewer SonarQube Dockerfile issue](https://github.com/dtcenter/METviewer/issues/527).
Can see DockerHub ‘docker scout’ [vulnerabilities here](https://hub.docker.com/layers/dtcenter/metviewer/develop/images/sha256-52a9cb6f67246f5926cf641143cd2ee29cd59cfdbf847385cdfd82a4451c6b00?context=repo&tab=vulnerabilities).
Step 1 - Update METviewer Dockerfile in place
Switch CentOS7 to Debian12.
Use Tomcat 9.0.89 and stick with Java 8.x
Step 2 - Switch to using new dtcenter/metviewer-base image
Upgrade to Java 11.x
Decide later if a Tomcat upgrade is also needed.

**Comment by JohnHalleyGotway** [comment]
On the `feature_527_met_base_image` feature branch, I modified `Dockerfile` and `Dockerfile.copy` to use a new `dtcenter/met-base-metviewer:v3.2` image. This [GHA run before that change](https://github.com/dtcenter/METviewer/actions/runs/9782052164) took 15m 19s to run the SonarQube scan, while this [GHA run after that change](https://github.com/dtcenter/METviewer/actions/runs/9783678994) only took 4m 16s to run.

So the SonarQube scan time is great improved, as hoped.
