### ISSUE TITLE
Update METviewer to run with Java 11 and a newer version of Tomcat

### ISSUE THREAD

**Issue by jprestop** [NCAR/METviewer#530]
## Describe the Task ##
Update METviewer to run with Java 11 and a newer version of Tomcat.  From Tatiana: This work will require a sysadmin's help with updating mohawk, dakota, and AWS. It is unlikely that the code will need a lot of updates due to these changes.

This arose from an update to mohawk (below is from Tatiana in an email with the subject "mohawk reboot today?" on April 3, 2024:

> The default Java version was changed on mohawk  after the reboot from Java 8 to Java 11
vxwww@mohawk:/opt/vxwww/tomcat$ java -version
openjdk version "11.0.22" 2024-01-16
All our apps are still using Java 8
Could you please revert the Java version to 8.

From Tatiana, here are the compatible Tomcat versions with Java 11:

> _**Tomcat 9.0.x and 10.1.x work with Java 11:
> https://tomcat.apache.org/whichversion.html
> ATEC project uses Tomcat 9.0.80.
> I would start testing with the latest version of Tomcat - currently it is 9.0.89 - and require 9.0.x**_

.

### Time Estimate ###
The developer should estimate this time.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] Use a Docker base image: dtcenter/metviewer-base that will be created by another issue (#534)
- [ ] Use Java 11.x with Tomcat 9.0.89 (Tomcat 9.0.89 should already be in the base image from work on issue #534)
- [ ] Determine if a further Tomcat upgrade is needed

Beta5

### Funding Source ###
Check in with Tara

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by bikegeek** [comment]
see issue 613: 
https://github.com/dtcenter/METviewer/issues/613
