### ISSUE TITLE
Generate a Docker image with Tomcat 9.0

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METviewer#534]
*Replace italics below with details for this issue.*

## Describe the Task ##
NRIT has identified that the version of Tomcat  (8.5.61) used on a RAL host machine has security vulnerabilities and needs to run Tomcat 8.5.96 (latest version is 8.5.100) 

Provide an updated METviewer container image with Tomcat 8.5.96 or above

UPDATE: 
Tomcat 9.0 is compatible with Java 8, use this version instead, as this may facilitate updating METviewer to Java 11 in issue #530

### Time Estimate ###
*Estimate the amount of work required here.*
Approximately 1.5-2 days to recreate a new Docker image, document the steps, and test.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] Find instructions for generating the Docker image
- [ ] Update the current Dockerfile to use Debian 12 and apt-get (replacing CentOS and yum, respectively)
- [ ] Test the updates
- [ ] Post to DockerHub

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** Minna Win
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **METviewer-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **METviewer-X.Y.Z** version, select the **METviewer-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METviewer-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by bikegeek** [comment]
This is addressed in METviewer issue https://github.com/dtcenter/METviewer/issues/527

it uses the met-base-metviewer image, where tomcat 9 is now used:
https://hub.docker.com/layers/dtcenter/met-base-metviewer/v3.2/images/sha256-85cf9d92238aebcb48966a37281bb85d97e47e21739d2d53c27ff45954fe67bc?context=explore
