### ISSUE TITLE
Create a Contributor's/Maintainer's Guide

### ISSUE THREAD

**Issue by jprestop** [NCAR/METviewer#535]
## Describe the Task ##
Create a Contributor's or a Maintainer's Guide.  Include information like how to load a database and instructions on restarting Tomcat when the METviewer application is unresponsive.

The NCAR production instance of METviewer hosted on the machine named "mohawk" is accessible here:
   https://dtcenter.ucar.edu/met/metviewer/metviewer1.jsp

The development instance of METviewer hosted on the machine named "dakota" is accessible here:
   http://dakota.rap.ucar.edu:8080/metviewer_dev/metviewer1.jsp

METviewer runs through tomcat. After "mohawk" or "dakota" are rebooted or when the METviewer application is unresponsive, tomcat needs to be restarted. This detail is included in the instructions for RAL-IT to do after rebooting these machines, but sometimes our team needs to do this task.

Here's how you restart Tomcat:

1. Log on to the machine (i.e. mohawk or dakota) as the 'vxwww' user.
   ssh -Y vxwww@mohawk.rap.ucar.edu
2. Find Tomcat in /opt/vxwww/tomcat:
   cd /opt/vxwww/tomcat
3. Run the shutdown script:
   bin/shutdown.sh
4. See if its still running:
   ps -ef | grep java | grep '/opt/vxwww/tomcat'
5. If so, manually kill it (e.g. kill -9 PID, where PID is the process-id found above).
6. Run 'ps -ef' command to confirm it's gone.
7. Restart tomcat:
  bin/startup.sh

### Time Estimate ###
TBD

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
TBD

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Review default **alert** labels
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **METviewer-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **METviewer-X.Y.Z** version, select the **METviewer-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METviewer-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
