### ISSUE TITLE
Add `testing.yaml` testing workflow

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METviewer#539]
## Describe the New Feature ##
Other METplus components include an automated `testing.yaml` testing workflow that's run through GitHub actions for each Pull Request. Recommend adding this automated testing for METviewer as well with logic very similar to the logic in METplus and MET.

This is related to work will help with issue: https://github.com/dtcenter/METplus-Internal/issues/36

Many more details need to be added here.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Determine where JUnit tests are located *
      - [ ] *If JUnit tests do not exist, create them*
- [ ] *Run the JUnit tests, if found within the IDE and from command line. *
- [ ] *Incorporate these tests into a Github Action workflow, leveraging any existing "base" workflows in the Github Marketplace, if possible*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Milestone and Projects ###
- [ ] Select **Milestone** as a **METviewer-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [ ] For a **METviewer-X.Y.Z** version, select the **METviewer-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METviewer-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by bikegeek** [comment]
Found junit tests in the java/edu/ucar/metviewer/test directory:

- AllTestRunner.java
- ComparePlotBatchTest.java
- CreatePlotBatchTest.java
- MVBatchTest.java

and 
AllTestCompare.java (created by NOAA contributor)

Determine how to run these tests then incorporate them into a Github action. 
*NOTE* running this within the IntelliJ IDE has highlighted that JUnit 3.8 or above is required for running these tests.
