### ISSUE TITLE
Support grouping data during scorecard creation

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METviewer#552]
## Describe the New Feature ##

From this METplus Discussion:
https://github.com/dtcenter/METplus/discussions/2734

It appears that the user needs to group input data while creating the scorecard, as specified in this issue:
https://github.com/dtcenter/METviewer/issues/16

However, it appears that this is not working, and produces this error message when attempting to group by fcst_lead:

`NameError: Derived curve can't be calculated. Multiple values for one valid date/fcst_lead`

Users will need to group data via MET's stat_analysis tool.  

From the METplus Discussion (John HG to Brianne N):

> @briannen I'm a bit surprised that METviewer does not already support grouping data by lead time directly, without first having to manually aggregate the data in Stat-Analysis.
> 
> I went hunting around and found https://github.com/dtcenter/METviewer/issues/16#issuecomment-506485210 from @TatianaBurek for issue https://github.com/dtcenter/METviewer/issues/16 from back in 2019 about this feature. Based on that comment, I did try grouping lead times like this in the scorecard XML:
> 
>         <columns>
>             <field name="vx_mask">
>                 <val name="NY" />
>                 <field equalize="true" name="fcst_lead">
>                     <val name="120000:240000" label="Day 1" />
>                     <val name="360000:480000" label="Day 2" />
>                 </field>
>             </field>
>         </columns>
> 
> But that produces the following type of error messages:
> 
> NameError: Derived curve can't be calculated. Multiple values for one valid date/fcst_lead
> 
> So that definitely does not work. I'm wondering if that feature DID exist in the old R-based version of METviewer but didn't survive the transition to Python?
> 
> Regardless, I certainly do see the ability to group the input data during scorecard creation as an incredibly useful feature. @bikegeek I'd recommend writing this up as a **feature request** since asking

 users to aggregate the data themselves ahead of time is a very high bar and very error prone.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Milestone and Projects ###
- [ ] Select **Milestone** as a **METviewer-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [ ] For a **METviewer-X.Y.Z** version, select the **METviewer-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] May require some additional work with METcalcpy components: scorecard.py and agg_stat.py

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METviewer-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by bikegeek** [comment]
this should be included in the upcoming scorecard development (database-independent version)

**Comment by bikegeek** [comment]
From the commit made for work related to issue #16:
https://github.com/dtcenter/METviewer/commit/8d8a27ae9a5ecebfd9613ec557ffc87d914efd40

it appears that in the R_work/include/agg_stat.R code (line 541), only fcst_valid_beg and fcst_init_beg are supported, but not fcst_lead

Looking in the METcalcpy/metcalcpy/agg_stat.py code, it appears that fcst_valid_beg and fcst_init_beg are treated in the same manner as the Rscript code.

The error message may not be due to the lack of support, but is identifying a legitimate error due to the lack of unique fcst_leads (in the _validate_series_cases_for_derived_operation).
